import { WeatherConditionMeta } from '../types';

export const WMO_CODE_MAP: Record<number, WeatherConditionMeta> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Cloudless, clear skies throughout the region',
    category: 'clear',
    accentColor: 'from-amber-400 to-orange-500',
    badgeBg: 'bg-amber-500/15 border-amber-500/30',
    badgeText: 'text-amber-400',
    iconName: 'Sun',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with scattered faint clouds',
    category: 'clear',
    accentColor: 'from-amber-300 to-sky-400',
    badgeBg: 'bg-amber-500/15 border-amber-500/30',
    badgeText: 'text-amber-300',
    iconName: 'SunDim',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Intermittent clouds with fair sunny periods',
    category: 'cloudy',
    accentColor: 'from-sky-400 to-slate-400',
    badgeBg: 'bg-sky-500/15 border-sky-500/30',
    badgeText: 'text-sky-300',
    iconName: 'CloudSun',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Dense cloud cover blocking direct sunlight',
    category: 'cloudy',
    accentColor: 'from-slate-400 to-slate-600',
    badgeBg: 'bg-slate-500/15 border-slate-500/30',
    badgeText: 'text-slate-300',
    iconName: 'Cloud',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Reduced visibility due to dense low-level mist',
    category: 'fog',
    accentColor: 'from-slate-400 to-zinc-500',
    badgeBg: 'bg-slate-500/15 border-slate-500/30',
    badgeText: 'text-slate-300',
    iconName: 'CloudFog',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Freezing fog forming crystalline frost deposits',
    category: 'fog',
    accentColor: 'from-cyan-400 to-slate-500',
    badgeBg: 'bg-cyan-500/15 border-cyan-500/30',
    badgeText: 'text-cyan-300',
    iconName: 'CloudFog',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Gentle, fine droplet precipitation',
    category: 'drizzle',
    accentColor: 'from-sky-400 to-blue-500',
    badgeBg: 'bg-sky-500/15 border-sky-500/30',
    badgeText: 'text-sky-300',
    iconName: 'CloudDrizzle',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Continuous light drizzle dampening surfaces',
    category: 'drizzle',
    accentColor: 'from-blue-400 to-indigo-500',
    badgeBg: 'bg-blue-500/15 border-blue-500/30',
    badgeText: 'text-blue-300',
    iconName: 'CloudDrizzle',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy drizzle with reduced ambient visibility',
    category: 'drizzle',
    accentColor: 'from-blue-500 to-indigo-600',
    badgeBg: 'bg-blue-500/15 border-blue-500/30',
    badgeText: 'text-blue-300',
    iconName: 'CloudRain',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Freezing drizzle causing icy surface patches',
    category: 'drizzle',
    accentColor: 'from-cyan-400 to-blue-600',
    badgeBg: 'bg-cyan-500/15 border-cyan-500/30',
    badgeText: 'text-cyan-300',
    iconName: 'CloudSnow',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Intense freezing drizzle creating slick icy glaze',
    category: 'drizzle',
    accentColor: 'from-cyan-500 to-blue-700',
    badgeBg: 'bg-cyan-500/15 border-cyan-500/30',
    badgeText: 'text-cyan-300',
    iconName: 'CloudSnow',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Intermittent light rain showers',
    category: 'rain',
    accentColor: 'from-blue-400 to-blue-600',
    badgeBg: 'bg-blue-500/15 border-blue-500/30',
    badgeText: 'text-blue-300',
    iconName: 'CloudRain',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady steady rainfall throughout the area',
    category: 'rain',
    accentColor: 'from-blue-500 to-indigo-600',
    badgeBg: 'bg-blue-500/15 border-blue-500/30',
    badgeText: 'text-blue-300',
    iconName: 'CloudRain',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Persistent heavy downpour with significant pooling',
    category: 'rain',
    accentColor: 'from-indigo-500 to-blue-700',
    badgeBg: 'bg-indigo-500/15 border-indigo-500/30',
    badgeText: 'text-indigo-300',
    iconName: 'CloudRainWind',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Sub-freezing rain creating hazardous road glazes',
    category: 'rain',
    accentColor: 'from-cyan-400 to-indigo-600',
    badgeBg: 'bg-cyan-500/15 border-cyan-500/30',
    badgeText: 'text-cyan-300',
    iconName: 'CloudSnow',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain leading to heavy ice accumulation',
    category: 'rain',
    accentColor: 'from-cyan-500 to-indigo-800',
    badgeBg: 'bg-cyan-500/15 border-cyan-500/30',
    badgeText: 'text-cyan-300',
    iconName: 'CloudSnow',
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    description: 'Light fluttering flurries with minor dusting',
    category: 'snow',
    accentColor: 'from-sky-200 to-indigo-400',
    badgeBg: 'bg-sky-400/15 border-sky-400/30',
    badgeText: 'text-sky-200',
    iconName: 'Snowflake',
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    description: 'Steady snowfall accumulating on cold ground',
    category: 'snow',
    accentColor: 'from-sky-300 to-indigo-500',
    badgeBg: 'bg-sky-400/15 border-sky-400/30',
    badgeText: 'text-sky-200',
    iconName: 'Snowflake',
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    description: 'Heavy blizzard-like snowfall with accumulation',
    category: 'snow',
    accentColor: 'from-slate-200 to-blue-500',
    badgeBg: 'bg-sky-400/15 border-sky-400/30',
    badgeText: 'text-sky-200',
    iconName: 'Snowflake',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Opaque white granular ice pellets',
    category: 'snow',
    accentColor: 'from-sky-300 to-slate-400',
    badgeBg: 'bg-sky-400/15 border-sky-400/30',
    badgeText: 'text-sky-200',
    iconName: 'Snowflake',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Passing brief showers with bright intervals',
    category: 'rain',
    accentColor: 'from-sky-400 to-blue-500',
    badgeBg: 'bg-sky-500/15 border-sky-500/30',
    badgeText: 'text-sky-300',
    iconName: 'CloudRain',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Sudden moderate shower bursts',
    category: 'rain',
    accentColor: 'from-blue-500 to-indigo-600',
    badgeBg: 'bg-blue-500/15 border-blue-500/30',
    badgeText: 'text-blue-300',
    iconName: 'CloudRain',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Torrential shower downpours with strong gusts',
    category: 'rain',
    accentColor: 'from-indigo-600 to-violet-700',
    badgeBg: 'bg-indigo-500/15 border-indigo-500/30',
    badgeText: 'text-indigo-300',
    iconName: 'CloudRainWind',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Scattered intermittent snow showers',
    category: 'snow',
    accentColor: 'from-sky-300 to-slate-400',
    badgeBg: 'bg-sky-400/15 border-sky-400/30',
    badgeText: 'text-sky-200',
    iconName: 'Snowflake',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow squalls with rapid accumulation',
    category: 'snow',
    accentColor: 'from-slate-300 to-indigo-600',
    badgeBg: 'bg-sky-400/15 border-sky-400/30',
    badgeText: 'text-sky-200',
    iconName: 'Snowflake',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Active electrical thunderstorm with thunder & lightning',
    category: 'thunderstorm',
    accentColor: 'from-amber-500 to-purple-700',
    badgeBg: 'bg-amber-500/15 border-amber-500/30',
    badgeText: 'text-amber-300',
    iconName: 'CloudLightning',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Light Hail',
    description: 'Thunderstorm accompanied by small hail stones',
    category: 'thunderstorm',
    accentColor: 'from-purple-600 to-indigo-900',
    badgeBg: 'bg-purple-500/15 border-purple-500/30',
    badgeText: 'text-purple-300',
    iconName: 'CloudHail',
  },
  99: {
    code: 99,
    label: 'Thunderstorm with Heavy Hail',
    description: 'Severe storm with intense lightning and damaging hail',
    category: 'thunderstorm',
    accentColor: 'from-red-600 to-purple-950',
    badgeBg: 'bg-red-500/15 border-red-500/30',
    badgeText: 'text-red-300',
    iconName: 'CloudHail',
  },
};

export function getWeatherCondition(code: number): WeatherConditionMeta {
  if (code in WMO_CODE_MAP) {
    return WMO_CODE_MAP[code];
  }
  return {
    code,
    label: 'Unknown Weather',
    description: 'Atmospheric conditions currently reporting code ' + code,
    category: 'cloudy',
    accentColor: 'from-slate-400 to-slate-600',
    badgeBg: 'bg-slate-500/15 border-slate-500/30',
    badgeText: 'text-slate-300',
    iconName: 'Cloud',
  };
}

export function isPrecipitation(code: number): boolean {
  return [51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 71, 73, 75, 77, 80, 81, 82, 85, 86, 95, 96, 99].includes(code);
}

export function isRainOrDrizzle(code: number): boolean {
  return [51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82, 95, 96, 99].includes(code);
}

export function isSnow(code: number): boolean {
  return [71, 73, 75, 77, 85, 86].includes(code);
}

export function isThunderstorm(code: number): boolean {
  return [95, 96, 99].includes(code);
}
